= Архитектура клиент-сервер

== Что представляет собой клиент-серверная архитектура?

Вычислительная или сетевая архитектура, в которой задания или сетевая нагрузка распределены между поставщиками услуг, называемыми серверами, и заказчиками услуг, называемыми клиентами. Фактически клиент и сервер — это программное обеспечение. Обычно эти программы расположены на разных вычислительных машинах и взаимодействуют между собой через сеть посредством сетевых протоколов, но они могут быть расположены также и на одной машине. Программы — сервера, ожидают от клиентских программ запросы и предоставляют им свои ресурсы в виде данных или сервисных функций.

== Какие преимущества клиент-серверной архитектуры?

Отсутствие дублирования кода программы-сервера программами-клиентами.
Так как все вычисления выполняются на сервере, то требования к компьютерам, на которых установлен клиент, снижаются.
Все данные хранятся на сервере, который, как правило, защищён гораздо лучше большинства клиентов. На сервере проще организовать контроль полномочий.

== Какие недостатки клиент-серверной архитектуры?

Неработоспособность сервера может сделать неработоспособной всю вычислительную сеть
Поддержка работы данной системы требует отдельного специалиста — системного администратора
Высокая стоимость оборудования"

== Что представляет собой трехуровневая архитектура клиент-сервер?

Предполагает наличие в ней 3-х компонентов:

* Клиента
* Сервера приложений, к которому подключено клиентское приложение
* Сервера баз данных, с которыми работает сервер приложений

== Что представляет собой многоуровневая архитектура клиент-сервер?

В двухуровневой архитектуре клиент-сервер приходится распределять три основные части приложения (хранение данных, обработка данных, интерфейс пользователя) по двум физическим модулям. Обычно хранение данных располагается на сервере, интерфейс пользователя на стороне клиента, а обработку приходится делить между клиентской и серверной частями, что может вызвать ряд сложностей. Для их решения используют многоуровневую архитектуру К-С.
многоуровневая архитектура - разновидность архитектуры, в которой функция обработки данных вынесена на один или несколько отдельных серверов, выполняющие функции сервера для интерфейсов с пользователем и функции клиента для серверов баз данных

== Что такое клиент?

Аппаратный или программный компонент вычислительной системы, посылающий запросы серверу.

Интерфейсный (обычно графический) компонент комплекса, предоставляемый конечному пользователю. Этот уровень не должен иметь прямых связей с базой данных (по требованиям безопасности и масштабируемости), быть нагруженным основной бизнес-логикой (по требованиям масштабируемости) и хранить состояние приложения (по требованиям надёжности). На этот уровень обычно выносится только простейшая бизнес-логика: интерфейс авторизации, алгоритмы шифрования, проверка вводимых значений на допустимость и соответствие формату, несложные операции с данными (сортировка, группировка, подсчёт значений), уже загруженными на терминал.

== Что такое сервер приложений?

Располагается на втором уровне, на нём сосредоточена большая часть бизнес-логики. Вне его остаются только фрагменты, экспортируемые на клиента, а также элементы логики, погруженные в базу данных. Реализация данного компонента обеспечивается связующим программным обеспечением. Серверы приложений проектируются таким образом, чтобы добавление к ним дополнительных экземпляров обеспечивало горизонтальное масштабирование производительности программного комплекса и не требовало внесения изменений в программный код приложения.

== Что такое сервер баз данных?

Средство не столько хранения и доступа, сколько обработки массивов информации. Через клиентские запросы запрашиваемая информация извлекается, данные обрабатываются, структурируются, изменяются в зависимости от настроек сервера. Руководят работой таких серверов СУБД (Системы Управления Базами Данных), самые известные из них - MS SQL Server, Oracle, MySQL.

Обеспечивает хранение данных и выносится на отдельный уровень, реализуется, как правило, средствами систем управления базами данных, подключение к этому компоненту обеспечивается только с уровня сервера приложений.

== Где выполняют обработку данных: на клиенте или сервере?

Чтобы избежать несогласованности различных элементов архитектуры, пытаются выполнять обработку данных либо на стороне клиента (толстый клиент) либо на сервере (тонкий клиент). У каждого подхода свои недостатки

== Что такое тонкий клиент?

Программа-клиент которая переносит большую часть задач по обработке информации на сервер

== Какие недостатки тонкого клиента?

Узкий функционал, невозможность работы при обрывах связи с сервером, чаще всего более низкое быстродействие

== Что такое толстый клиент?

Программа-клиент обеспечивающая расширенную функциональность независимо от центрального сервера. Часто сервер в этом случае является лишь хранилищем данных, а вся работа по обработке и представлению этих данных переносится на машину клиента.

== Какие недостатки толстого клиента?

Перезагружается сеть, из-за передачи необработанных, а значит избыточных данных.
Усложняется поддержка и изменение системы, любое изменение требует замены всех интерфейсных программ
Наличие бизнес-логики

== Как осуществляется взаимодействие клиента с сервером?

Для взаимодействия с клиентом (или клиентами, если поддерживается одновременная работа) сервер выделяет необходимые ресурсы межпроцессного взаимодействия и ожидает запросы на открытие соединения (или, собственно, запросы на предоставляемый сервис). В зависимости от типа такого ресурса, сервер может обслуживать процессы в пределах одной компьютерной системы или процессы на других машинах через каналы передачи данных (например, COM-порт) или сетевые соединения.
Формат запросов клиента и ответов сервера определяется протоколом. Спецификации открытых протоколов описываются открытыми стандартами, например, протоколы Интернета определяются в документах RFC.
В зависимости от выполняемых задач одни серверы, при отсутствии запросов на обслуживание, могут простаивать в ожидании. Другие могут выполнять какую-то работу (например, работу по сбору информации), у таких серверов работа с клиентами может быть второстепенной задачей."

== Что такое серверное ПО?

Программный компонент выполняющий сервисные функции по запросу клиента, предоставляя ему доступ к определённым ресурсам или услугам.

== Что такое бизнес-логика?

Реализация предметной области в информационной системе.

== Что такое протокол передачи данных?

Набор соглашений интерфейса логического уровня, которые определяют обмен данными между различными программами. Эти соглашения задают единообразный способ передачи сообщений и обработки ошибок при взаимодействии программного обеспечения разнесённой в пространстве аппаратуры, соединённой тем или иным интерфейсом.

== Что такое web-сервер (сервер web-приложений)?

Сервер, принимающий HTTP-запросы от клиентов, обычно веб-браузеров, и выдающий им HTTP-ответы, как правило, вместе с HTML-страницей, изображением, файлом, медиа-потоком или другими данными.

== Что такое proxy-сервер?

Посредник между пользователями локальной сети и Интернетом. Обеспечивает безопасный выход в интернет, защищая от нежелательного доступа извне и при необходимости ограничивая выход на определенные ресурсы пользователям локальной сети. Кроме того, выполняет ряд других функций: учет и экономия трафика путем сжатия данных, кэширование, анонимизация доступа.

== Что такое ftp-сервер?

Их задача – перемещать файлы по запросу простых файловых менеджеров с помощью стандартного протокола File Transfer Protocol.

== Что такое процесс (в рамках ОС)?

Программа, которая выполняется в текущий момент.

== Что такое демон?

Компьютерная программа в системах класса UNIX, запускаемая самой системой и работающая в фоновом режиме без прямого взаимодействия с пользователем.

== Что такое файловый сервер?

Серверы для обеспечения доступа к файлам на диске сервера.

== Что такое принт-сервер (сервер печати)?

Позволяет использовать одно печатающее устройство для обслуживания нескольких компьютеров.

== Что такое почтовый сервер, сервер сообщений?

Основная задача такого сервера состоит в распознавании адресов входящей электронной корреспонденции и распределении ее по ящикам интрасети, а также отправку исходящей, обеспечение внутренней переписки.

== Что такое менеджер транзакций?

Программа или комплекс программ, с помощью которых можно согласовать работу различных компонентов информационной системы.
Позволяют одному серверу приложений одновременно обмениваться данными с несколькими серверами баз данных.

== Что такое контроллер домена?

Главный компьютер в локальной сети, имеющей иерархическую структуру – домене. Через контроллер домена осуществляется централизованное управление ресурсами домена – учетными записями компьютеров и пользователей.

== Что такое сервер рабочей группы?

Многофункциональное аппаратное решение для группы компьютеров. Объединяет в себе возможности файлового сервера, сервера приложений, базы данных, принт/факс-сервера, почтового и других, в зависимости от потребностей. При общем использовании сервер рабочей группы обязан разграничивать доступ к данным и права пользователей.
