= CSS

== Что такое CSS?

Cascading Style Sheets (каскадные таблицы стилей) - формальный язык описания внешнего вида документа, написанного с использованием языка разметки. Преимущественно используется как средство описания, оформления внешнего вида веб-страниц, написанных с помощью HTML, но может также применяться к любым XML-документам, например, к SVG или XUL.

== Какая цель создания CSS?

CSS используется создателями веб-страниц для задания цветов, шрифтов, расположения отдельных блоков и других аспектов представления внешнего вида этих веб-страниц. Основной целью разработки CSS являлось разделение описания логической структуры веб-страницы, которое производится с помощью HTML или других языков разметки, от описания внешнего вида этой веб-страницы, производимую теперь с помощью формального языка CSS). Такое разделение может увеличить доступность документа, предоставить большую гибкость и возможность управления его представлением, а также уменьшить сложность и повторяемость в структурном содержимом. Кроме того, CSS позволяет представлять один и тот же документ в различных стилях или методах вывода, таких как экранное представление, печатное представление, чтение голосом (специальным голосовым браузером или программой чтения с экрана), или при выводе устройствами, использующими шрифт Брайля.

== Какие преимущества CSS?

Несколько дизайнов страницы для разных устройств просмотра
Уменьшение времени загрузки страниц сайта за счет переноса правил представления данных в отдельный CSS-файл. В этом случае браузер загружает только структуру документа и данные, хранимые на странице, а представление этих данных загружается браузером только один раз и может быть закешировано.
Простота последующего изменения дизайна. Не нужно править каждую страницу, а достаточно лишь изменить CSS-файл.
Дополнительные возможности оформления. Например, сделать так, чтобы меню было всегда видно при прокрутке страницы.

== Какие недостатки CSS?

Различное отображение вёрстки в различных браузерах (особенно устаревших), которые по-разному интерпретируют одни и те же данные CSS.
Часто встречающаяся необходимость на практике исправлять не только один CSS-файл, но и теги HTML, которые сложным и ненаглядным способом связаны с селекторами CSS, что иногда сводит на нет простоту применения единых файлов стилей и значительно увеличивает время редактирования и тестирования.

== Как подключить CSS?

Правила CSS пишутся на формальном языке CSS и располагаются в таблицах стилей, то есть таблицы стилей содержат в себе правила CSS. Эти таблицы стилей могут располагаться как в самом веб-документе, внешний вид которого они описывают, так и в отдельных файлах, имеющих формат CSS. (По сути, формат CSS — это обычный текстовый файл. В файле .css не содержится ничего, кроме перечня правил CSS и комментариев к ним.)
То есть, эти таблицы стилей могут быть подключены, внедрены в описываемый ими веб-документ четырьмя различными способами

== Как использовать внешнюю таблицу стилей, способ link?

Когда таблица стилей находится в отдельном файле, она может быть подключена к веб-документу посредством тега <link>, располагающегося в этом документе между тегами <head> и </head>. (Тег <link> будет иметь атрибут href, имеющий значением адрес этой таблицы стилей). Все правила этой таблицы действуют на протяжении всего документа

<link rel=""stylesheet"" href=""style.css"">

== Как использовать внешнюю таблица стилей, способ style + import?

Когда таблица стилей находится в отдельном файле, она может быть подключена к веб-документу посредством директивы @import, располагающейся в этом документе между тегами <style> и </style> (которые, в свою очередь, располагаются в этом документе между тегами <head> и </head>) сразу после тега <style>, которая также указывает (в своих скобках, после слова url) на адрес этой таблицы стилей. Все правила этой таблицы действуют на протяжении всего документа

<style media=""all"">
@import url(style.css);
</style>

== Как использовать внутреннюю таблицу стилей ко всему документу?

Когда таблица стилей описана в самом документе, она может располагаться в нём между тегами <style> и </style> (которые, в свою очередь, располагаются в этом документе между тегами <head> и </head>). Все правила этой таблицы действуют на протяжении всего документа

<style>
body {
    color: red;
}
</style>

== Как использовать внутреннюю таблицу стилей к тэгу?

Когда таблица стилей описана в самом документе, она может располагаться в нём в теле какого-то отдельного тега (посредством его атрибута style) этого документа. Все правила этой таблицы действуют только на содержимое этого тега

<body>
<p style=""font-size: 20px; color: green; font-family: arial, helvetica, sans-serif"">
...
</p>
</body>

== Какие правила построения CSS?

В первых трёх случаях подключения таблицы CSS к документу каждое правило CSS из таблицы стилей имеет две основные части — селектор и блок объявлений. Селектор, расположенный в левой части правила, определяет, на какие части документа распространяется правило. Блок объявлений располагается в правой части правила. Он помещается в фигурные скобки, и, в свою очередь, состоит из одного или более объявлений, разделённых знаком «;». Каждое объявление представляет собой сочетание свойства CSS и значения, разделённых знаком ":". Селекторы могут группироваться в одной строке через запятую. В таком случае свойство применяется к каждому из них.
В четвёртом случае подключения таблицы CSS к документу правило CSS (являющееся значением атрибута style тега, на который оно действует) представляет собой перечень объявлений («свойство CSS : значение»), разделённых знаком «;»

== Что собой представляет универсальный селектор?

Применяется ко всем атрибутам

* {
margin: 0;
padding: 0;
}

== Что собой представляет селектор тегов?

Применяется к тегам

p {
font-family: arial, helvetica, sans-serif;
}

== Что собой представляет селектор классов?

Применяется к классам

.note {
   color: red;
   background-color: yellow;
   font-weight: bold;
}

== Что собой представляет селектор идентификаторов?

Применяется к идентификаторам

#paragraph1 {
margin: 0;
}

== Что собой представляет селектор атрибутов?

Применяется к тегам с конкретным значением атрибута

a[href=""http://www.somesite.com""] {
font-weight: bold;
}

== Что собой представляет селектор потомков (контекстный селектор)?

Применится ко всем тегам, которые являются потомками впереди стоящего тега

h1 em {
    color: red;
}

== Что собой представляет селектор дочерних элементов?

Применяется для всех элементов, которые являются дочерними к слевастоящему элементу

p.note > b {
color: green;
}

== Что собой представляет селектор сестринских элементов?

Выбор второго следующего сразу за первым если у них общий родитель

h1 + p {
font-size: 24pt;
}

== Что собой представляет селектор псевдоклассов?

Псевдокласс - определяет динамическое состояние элемента
:active - применится при активации пользователем элемента
:link - применится к не посещенным ссылкам
:focus - к элементу при получении им фокуса
:hover - курсор в пределах элемента
:visited, :first-child, :lang ит.п.

a:active {
color: blue;
}

== Что собой представляет селектор псевдоэлементов?

Псевдоэлемент - позволяет задать стиль элементов, не определенных в дереве элементов и генерировать содержимое которого нет в исходном коде текста.

* :after - вставка контента после элемента
* :before
* :first-letter - стиль первого символа в тексте элемента
* :first-line

p:first-letter {
    font-size: 32px;
}

== Что такое классы и идентификаторы элементов?

Класс или идентификатор может быть присвоен какому-нибудь элементу (тегу) HTML посредством атрибутов class или id этого элемента (тега)

<div id=""First"">
<p class=""Big"">"
Какие основные отличия классов от идентификаторов элементов?	"Идентификатор предназначен для одного элемента, тогда как класс обычно присваивают сразу нескольким. Тем не менее, современные браузеры, как правило, корректно отображают множественные элементы с одинаковым идентификатором. Также отличие в том, что могут существовать множественные классы (когда класс элемента состоит из нескольких слов, разделённых пробелами). Для идентификаторов такое невозможно.
Идентификаторы широко используются в JavaScript для нахождения уникального элемента в документе.

== На чем основано применение CSS к HTML странице?

Применение CSS к документам HTML основано на принципах наследования и каскадирования.

== Что такое принцип наследования?

Свойства CSS, объявленные для элементов-предков, наследуются элементами потомками. Но, естественно, не все свойства CSS наследуются — например, если для тега параграфа p средствами CSS задана рамка, то она не будет наследоваться ни одним тегом, содержащимся в данном теге p. Так сделано в предположении, что обрамление всех-всех вложений в тег — менее тривиальная задача, чем задание одиночной рамки. А вот если для параграфа p средствами CSS задан цвет шрифта (например, color:green;), то это свойство будет унаследовано каждым элементом-тегом, находящимся в параграфе, до тех пор, пока этому тегу не будет назначен свой цвет шрифта. Который, в свою очередь, будет теперь наследоваться всеми вложенными в него подэлементами, не распространяясь на элементы-соседи тега.

== Что такое принцип каскадирования?

Принцип каскадирования применяется в случае, когда какому-то элементу HTML одновременно поставлено в соответствие более одного правила CSS, то есть, когда происходит конфликт значений этих правил. Чтобы разрешить такие конфликты, вводятся правила приоритета.

== Какие правила применяются для приоритета стилей?

1)Наиболее низким приоритетом обладает стиль браузера;
2)Следующим по значимости является стиль, заданный пользователем браузера в его настройках
3)И наиболее высоким приоритетом обладает стиль, заданный непосредственно автором страницы. Приоритеты далее расставляются следующим образом:
3.1)Самым низким приоритетом обладают стили, наследуемые в документе элементом от своих предков
3.2)Более высоким приоритетом обладают стили, заданные во внешних таблицах стилей, подключённых к документу
3.3)Ещё более высоким приоритетом обладают стили, заданные непосредственно селекторами всех десяти видов, содержащимися в контейнерах style данного документа. Нередки случаи, когда к какому-нибудь элементу имеют отношение, задают его вид, несколько таких селекторов. Такие конфликты между ними разрешаются с помощью расчёта специфичности каждого такого селектора и применения этих селекторов к данному элементу в порядке убывания их специфичностей. При расчёте специфичности селектора принимается во внимание:
3.3.1)количество идентификаторов (#id) в селекторе — ((1,0,0) за каждый объявленный идентификатор в селекторе правила CSS)
3.3.2)количество классов (.class), атрибутов ([attr], [attr=""value""]) и псевдоклассов (:pseudo-class) в селекторе — ((0,1,0) за каждый объявленный класс, атрибут и псевдокласс в селекторе правила CSS)
3.3.3)количество элементов (h1, input) и псевдоэлементов (::pseudo-element) в селекторе — ((0,0,1) за каждый объявленный элемент и псевдоэлемент в селекторе правила CSS).
Принцип расчёта таков, что, например, (1,0,0) будет иметь большую специфичность, соответственно — больший приоритет, чем даже (0,10,0), (0,1,0) будет иметь большую специфичность, больший приоритет, чем (0,0,10). Если же рассчитанные таким образом специфичности окажутся одинаковыми, то к элементу будет применено правило, описанное селектором, расположенным в документе ниже других.
3.4)Ещё более высоким приоритетом обладают стили, объявленные непосредственно в теге данного элемента посредством атрибута style этого тега;
3.5)И наконец самым высоким приоритетом обладают стили, объявленные автором страницы или пользователем, с помощью сопроводительного слова !important. Если таких свойств несколько, то предпочтение отдаётся в первую очередь стилям, заданным пользователем, а для остальных свойств (которые будут являться задаваемыми автором страницы) потребуется определить их специфичности по принципам, описанным выше, и применять эти свойства в порядке убывания этих их специфичностей.

== Что такое условные комментарии?

Механизм, при помощи которого автор веб-страницы может использовать нестандартные особенности некоторых браузеров, избегая проблем несовместимости с другими браузерами.
В настоящее время условные комментарии можно использовать для написания специального кода, предназначенного для Internet Explorer. Следующим образом, например, можно включить специальные правила CSS, предназначенные для этого браузера:

<!--[if IE]><link rel=""stylesheet"" type=""text/css"" href=""ie.css""><![endif]-->

Другой вид условных комментариев, также применяющийся только в браузерах Internet Explorer — комментарии, добавляемые к коду программы на JScript:

if ( /*@cc_on ! @*/ false ) {
// код, специфический для Internet Explorer версий ≤ 10
}

Данная конструкция работает, так как после раскрытия условных комментариев упомянутые версии браузеров увидят проверку if(  !  false ), что даст истинный результат; остальные браузеры воспримут комментарии как обычные неисполняемые фрагменты программы, и получат if(  false )

== Что такое CSS Framework?

Заранее подготовленная CSS-библиотека, созданная для упрощения работы верстальщика, быстроты разработки и исключения максимально возможного числа ошибок вёрстки (проблемы совместимости различных версий браузеров и т. д.) Так же как и библиотеки скриптовых языков программирования, CSS-фреймворки, обычно имеющие вид внешнего .css-файла, «подключаются» к проекту (добавляются в заголовок веб-страницы), позволяя неискушённому в тонкостях вёрстки программисту или дизайнеру правильно создать html-макет.

== Что такое расширения CSS?

Часто при вёрстке страниц нужно использовать одно и то же значение много раз: один и тот же цвет, один и тот же шрифт. И если это значение нужно будет изменить, то придётся менять во многих местах. В стандартном CSS нет возможностей наследования стилей, вычисляемых значений и прочих зависимостей.
Для решения этих вопросов и ускорения разработки существует несколько расширений языка CSS. Расширений в том смысле, что код CSS является валидным кодом для расширения, но не наоборот. Чтобы из кода «расширенного CSS» получился обычный CSS-файл, воспринимаемый браузером, необходимо выполнить компиляцию. Компиляция может быть нескольких типов:
- во время запуска страницы на стороне клиента (средствами JavaScript)
- во время запуска страницы на стороне сервера
- во время вёрстки сайта средствами специального компилятора

== Приведите примеры CSS.

p {
font-family: arial, helvetica, sans-serif;
}
элементы p(абзацы) будут отображаться arial, если такого шрифта нет - helvetica ит.п.

h2 {
font-size: 20pt;
color: red;
background: white;
}
элементы h2(заголовки второго уровня) будут отображаться красным на белом фоне с увеличенным размером

.note {
    color: red;
    background-color: yellow;
    font-weight: bold;
}
любые элементы класса note будут выведены полужирным шрифтом красного цвета на желтом фоне

p#paragraph1 {
padding-left: 10px;
}
элементы p c id paragraph1 будут иметь внутренний отступ в 10 пикселей

a:hover {
text-decoration: none;
}
убирает подчеркивание для элементов a (гиперссылки) при наведении курсора

#news p {
color: blue;
}
элементы p которые находятся внутри элементов с id news будут отображаться синим

[type=""button""] {
background-color: green;
}
для всех элементов с type равным button будут отображаться на зеленом фоне

== Как подключить CSS к XML?

<?xml-stylesheet type="text/css" href="style.css"?>

== Какие существуют CSS-трюки?

Различия в реализации CSS различными браузерами заставляют веб-разработчиков искать решения, как заставить все браузеры отображать страницу одинаково. CSS-фильтры (также часто называемые CSS-хаками) позволяют выборочно применять (или не применять) стили к различным элементам. Например, известно, что Internet Explorer 6 применяет правила, использующие селекторы вида * html селектор (фильтр, известный как «star html bug»).

/* Следующее правило применит только IE6. */
* html #someblock { width: 100px; padding: 10px; }"
