= HTML

== Что такое web-страница?

Документ или информационный ресурс Всемирной паутины, доступ к которому осуществляется с помощью веб-браузера.

== Что такое динамическая web-страница?

Динамическая веб-страница - сгенерирована программно, в отличие от статичной страницы, которая является просто файлом, лежащим на сервере. Сервер генерирует HTML-код динамической страницы для обработки браузером или другим агентом пользователя.

== Что такое сайт?

Совокупность логически связанных между собой веб-страниц

== Что такое язык разметки?

Набор символов или последовательностей, вставляемых в текст для передачи информации о его выводе или строении

== Что такое HTML?

Язык гипертекстовой разметки - стандартизированный язык разметки документов во Всемирной паутине. Большинство веб-страниц содержат описание разметки на языке HTML (или XHTML). Язык HTML интерпретируется браузерами; полученный в результате интерпретации форматированный текст отображается на экране монитора компьютера или мобильного устройства.

== Что такое HTML элемент?

HTML — теговый язык разметки документов. HTML элемент - это основная структурная единица веб-страницы, написанная на языке HTML. Любой документ на языке HTML представляет собой набор элементов, причём начало и конец каждого элемента обозначается специальными пометками — тегами. Элементы могут быть пустыми, то есть не содержащими никакого текста и других данных (например, тег перевода строки <br>). В этом случае обычно не указывается закрывающий тег. Кроме того, элементы могут иметь атрибуты, определяющие какие-либо их свойства (например, размер шрифта для тега <font>). Атрибуты указываются в открывающем теге.

== Что такое tag?

Именованная метка. В SGML (HTML, WML, AmigaGuide, языках семейства XML) — элемент языка разметки гипертекста. Текст, содержащийся между начальным и конечным тегом, отображается и размещается в соответствии со свойствами, указанными в начальном теге.

== Что представляет собой декларация (HTML 5)?

Метаинформация о типе документа

<!DOCTYPE html>"
Для чего предназначен tag </a>?	" Гиперссылка, Якорь

<a href=""filename"" target=""_self"">название ссылки</a>

== Для чего предназначен tags </h1> …. </h6>?

Заголовки 1-6 уровня (от крупных к мелким)

== Для чего предназначен tag </p>?

Новый абзац

== Для чего предназначен tag <br>?

Новая строка

== Для чего предназначен tag <hr>?

Горизонтальная линия

== Для чего предназначен tag </blockquote>?

Цитата

== Для чего предназначен tag </pre>?

Режим превью (все теги кроме pre игнорируются)

== Для чего предназначен tag </div>?

Блок(обычно используется для применения стилей CSS)

== Для чего предназначен tag </span>?

Строка (обычно используется для применения стилей CSS)

== Для чего предназначен tag </em>?

Логическое ударение (обычно отображается курсивным шрифтом)

== Для чего предназначен tag </strong>?

Усиленное логическое ударение (обычно отображается жирным шрифтом)

== Для чего предназначен tag </i>?

Выделение текста курсивом

== Для чего предназначен tag </b>?

Выделение текста жирным шрифтом

== Для чего предназначен tag </u>?

Подчёркивание текста

== Для чего предназначен tag </s> или </strike>?

Зачёркивание текста

== Для чего предназначен tag </sub>?

Подстрочный текст

== Для чего предназначен tag </sup>?

Надстрочный текст

== Для чего предназначен tag </li>?

Элемент списка

== Для чего предназначен tag </ul>?

Ненумерованный список

 <ul>
   <li> первый элемент </li>
   <li> второй элемент </li>
   <li> третий элемент </li>
 </ul>

== Для чего предназначен tag </ol>?

Нумерованный список

<ol type=""i"">
<li> Первое </li>
<li> Второе </li>
<li> И т.д. </li>
</ol>

== Для чего предназначен tag </script>?

Вставка скриптов

== Для чего предназначен tag <img ... />?

Вставка изображения. Этот тег не закрывается
src - имя или URL
alt - альтернативное имя
title - краткое описание
width, height - размеры
align - обтекание текстом
vspace, hspace - пространство вокруг

<img src=""url"" alt=""текст"" title=""текст"" width=""размер (пикс, %)"" height=""размер (пикс, %)"">

== Для чего предназначен tag </table>?

Создание таблицы
border - толщина линий
cellspacing - расстояние между клетками
cellpadding - отступ от рамки до содержимого ячейки
height - высота таблицы
width - ширина таблицы

<table border=""1"" cellspacing=""0"">
<caption>Улов крокодилов в Мумбе-Юмбе</caption>
<th>Год</th>
<th>Улов</Tth>
<tr>
<td>1997</td>
<td>214</td>
</tr>
<tr>
<td>1998</td>
<td>216</td>
</tr>
<tr>
<td>1999</td>
<td>207</td>
</tr>
</table>

== Для чего предназначен tag </caption>?

Заголовок таблицы

== Для чего предназначен tag </tr>?

Строка таблицы

== Для чего предназначен tag </th>?

Заголовок столбца таблицы

== Для чего предназначен tag </td>?

Ячейка таблицы

== Для чего предназначен tag </form>?

Создание формы (раздела документа, позволяющего пользователю вводить информацию для последующей обработки системой)
Для отправки формы имеются два метода: GET и POST. Метод GET рекомендуется использовать в случаях, когда при обработке формы на стороне сервера не происходит побочных действий, например, поиск. В противном случае, когда на стороне сервера подразумевается модификация в базах данных и т. п., требуется использовать метод POST.

== Для чего предназначен tag </input>?

Элемент ввода (может иметь разные функции - от ввода текста до отправки формы)

== Для чего предназначен tag </textarea>?

Текстовая область (многострочное поле для ввода текста)

== Для чего предназначен tag </select>?

Список (обычно в виде выпадающего меню)

== Для чего предназначен tag </option>?

Пункт списка
Для чего предназначен tag <font ...> … </font>?	"Задание параметров шрифта
color=цвет
face=шрифт
size=размер
size=+-изменение

<font size=""+2"">больших</font>
<font color=""green"">зелёных</font>

== Для чего предназначен tag </big>?

Увеличение шрифта

== Для чего предназначен tag </small>?

Уменьшение шрифта

== Для чего предназначен tag </blink>?

Мигающий текст

== Для чего предназначен tag </marquee>?

Сдвигающийся по экрану текст

== Для чего предназначен tag </map>?

Создание карты изображений - графического объект языка разметки HTML, связанного с изображением и содержащем специальные области (активные зоны), при нажатии на которые происходит переход по-определённому URL (при помощи javascript можно установить другие действия). Использование карт изображений позволяет хранить несколько ссылок в одном изображении.

== Для чего предназначен tag </dl>?

Список определений

<dl>
<dt> Кошка </dt> <dd> мяукающее домашнее животное </dd>
<dt> Кот </dt> <dd> муж кошки </dd>
<dt> Крокодил </dt> <dd> большой африканский зверь с острыми зубами </dd>
</dl>

== Для чего предназначен tag </embed>?

Вставка различных объектов: не-HTML документов и media-файлов

== Для чего предназначен tag </applet>?

Вставка Java-апплетов

== Что такое MHTML?

MIME HTML - архивный формат веб-страниц, используемый для комбинирования кода HTML и ресурсов, которые обычно представлены в виде внешних ссылок (изображения, анимации Flash, Java-апплеты и аудиофайлы) в один файл.

== Что такое XHTML?

Расширяемый язык гипертекстовой разметки. Семейство языков разметки веб-страниц на основе XML, повторяющих и расширяющих возможности HTML 4. Развитие остановлено, использовать не рекомендуется

== Что такое SGML?

Стандартный обобщённый язык разметки - метаязык, на котором можно определять язык разметки для документов. Языки HTML и XML произошли от SGML.

== Что такое java-апплет?

Прикладная программа, чаще всего написанная на языке программирования Java в форме байт-кода. Java-апплеты выполняются в веб-обозревателе с использованием виртуальной Java машины. Java-апплеты обычно пишутся на языке программирования Java, но могут быть написаны и на других языках, которые компилируются в байт‐код Java.

== Что такое PHP?

Препроцессор гипертекста - скриптовый язык общего назначения, интенсивно применяемый для разработки веб-приложений. В настоящее время поддерживается подавляющим большинством хостинг-провайдеров и является одним из лидеров среди языков, применяющихся для создания динамических веб-сайтов

== Что такое framework (фреймворк)?

Программная платформа, определяющая структуру программной системы; программное обеспечение, облегчающее разработку и объединение разных компонентов большого программного проекта. Употребляется также слово «каркас». Можно также говорить о каркасном подходе как о подходе к построению программ, где любая конфигурация программы строится из двух частей:
Постоянная часть — каркас, не меняющийся от конфигурации к конфигурации и несущий в себе гнёзда, в которых размещается вторая, переменная часть;
Сменные модули (или точки расширения).
