= JavaScript

== Что такое JavaScript?

Прототипно-ориентированный сценарный язык программирования. JavaScript обычно используется как встраиваемый язык для программного доступа к объектам приложений. Наиболее широкое применение находит в браузерах как язык сценариев для придания интерактивности веб-страницам

== Какие основные архитектурные черты JavaScript?

- Динамическая типизация
- Слабая типизация
- Автоматическое управление памятью
- Прототипное программирование
- Функции как объекты первого класса

== Что такое динамическая типизация?

Приём при котором переменная связывается с типом в момент присваивания значения, а не в момент объявления переменной.

== Что такое слабая типизация?

Сильная и слабая типизации характеризуются наличием или отсутствием безопасности согласования типов и безопасности доступа к памяти, а также характерным временем осуществления такого контроля (в статике или в динамике).

== Что значит автоматическое управление памятью?

Одна из форм автоматического управления памятью. Специальный процесс, называемый сборщиком мусора (англ. garbage collector), периодически освобождает память, удаляя объекты, которые уже не будут востребованы приложениями.

== Что такое прототипное программирование?

Стиль объектно-ориентированного программирования, при котором отсутствует понятие класса, а наследование производится путём клонирования существующего экземпляра объекта — прототипа

== Что значит функции как объекты первого класса?

В контексте конкретного языка программирования так называются элементы, которые могут быть переданы как параметр, возвращены из функции, присвоены переменной

== Как выглядит структура языка?

Структурно JavaScript можно представить в виде объединения трёх чётко различимых друг от друга частей:
- Ядро
- Объектная модель браузера
- Объектная модель документа (Document Object Model)

== Что такое ядро?

ECMAScript не является браузерным языком и в нём не определяются методы ввода и вывода информации. Это, скорее, основа для построения скриптовых языков. Спецификация ECMAScript описывает типы данных, инструкции, ключевые и зарезервированные слова, операторы, объекты, регулярные выражения, не ограничивая авторов производных языков в расширении их новыми составляющими.

== Что такое объектная модель браузера (Browser Object Model)?

Браузер-специфичная часть языка, являющаяся прослойкой между ядром и объектной моделью документа. Основное предназначение объектной модели браузера - управление окнами браузера и обеспечение их взаимодействия. Каждое из окон браузера представляется объектом window, центральным объектом DOM.
Помимо управления окнами, в рамках объектной модели браузера, браузерами обычно обеспечивается поддержка следующих сущностей:

- управление фреймами,
- поддержка задержки в исполнении кода и зацикливания с задержкой,
- системные диалоги,
- управление адресом открытой страницы,
- управление информацией о браузере,
- управление информацией о параметрах монитора,
- ограниченное управление историей просмотра страниц,
- поддержка работы с HTTP cookie.

== Что такое объектная модель документа (Document Object Model)?

Интерфейс программирования приложений (API) для HTML и XML-документов. Согласно DOM, документ (например, веб-страница) может быть представлен в виде дерева объектов, обладающих рядом свойств, которые позволяют производить с ним различные манипуляции:

- генерация и добавление узлов,
- получение узлов,
- изменение узлов,
- изменение связей между узлами,
- удаление узлов.

== Как связан JavaScript c другими языками?

На JavaScript реализованы интерпретаторы ряда языков программирования, что позволяет использовать для них как среду выполнения веб-браузер.

== Что можно сказать о безопасности JavaScript?

JavaScript позволяет потенциальным авторам вредоносного кода запускать его на любом компьютере сети: для этого достаточно открыть на нём веб-страницу. Это обуславливает наличие двух принципиальных ограничений:

- JavaScript-программы выполняются в песочнице, в которой они могут выполнять только ограниченный круг действий, а не задачи программирования общего назначения (например, создание файлов, работа с сокетами),
- для JavaScript-кода применяется политика общего происхождения, в соответствии с которой скрипт, встроенный в страницу, не может получить доступ к ряду свойств объектов другой страницы (в частности, к большинству свойств объекта document) при отличии в протоколе, хосте и номере порта этих страниц.

== Что такое ненавязчивый JavaScript?

Подходом к web-программированию на языке JavaScript. Под принципами ненавязчивого Javascript обычно понимаются следующие:
- отделение функциональности веб-страницы («уровень поведения») от структуры, содержания и представления Web-страницы
- наработанные методы по избежанию проблем традиционного программирования на JavaScript (зависимость от браузера и недостаток масштабируемости ит.д.)
- техники «постепенного улучшения»  для поддержки пользовательских агентов, которые могут не в полной мере поддерживать функциональность JavaScript

== Какие существуют способы встраивание JS в веб-страницы?

- Расположение внутри страницы
- Расположение внутри страницы
- Вынесение в отдельный файл

== Как расположить JS-код внутри страницы?

Для добавления JavaScript-кода на страницу, можно использовать теги <script></script>, которые рекомендуется, но не обязательно, помещать внутри контейнера <head>. Контейнеров <script> в одном документе может быть сколько угодно. Атрибут «type='text/javascript'» указывать необязательно, данное значение используется по умолчанию. Скрипт, выводящий модальное окно с классической надписью «Hello, World!» внутри браузера:
<script type=""application/javascript"">
alert('Hello, World!');
</script>

== Как расположить JS-код внутри тега?

Спецификация HTML описывает набор атрибутов, используемых для задания обработчиков событий. Пример использования:
<a href=""delete.php"" onclick=""return confirm('Вы уверены?');"">
Удалить
</a>
В приведённом примере при нажатии на ссылку функция confirm('Вы уверены?'); вызывает модальное окно с надписью «Вы уверены?», а return false; блокирует переход по ссылке. Разумеется, этот код будет работать только если в браузере есть и включена поддержка JavaScript, иначе переход по ссылке произойдёт без предупреждения.
Использование кода JavaScript в контексте разметки страницы расценивается в рамках ненавязчивого JavaScript как плохая практика. Аналогом (при условии снабжения ссылки идентификатором alertLink)
<a href=""delete.php"" id=""alertLink"">
Удалить
</a>
приведённого примера может являться, например, следующий фрагмент JavaScript:
window.onload = function() {
var linkWithAlert = document.getElementById(""alertLink"");
linkWithAlert.onclick = function() {
return confirm('Вы уверены?');
};
};

== Как вынести JS-код в отдельный файл?

Есть и третья возможность подключения JavaScript — написать скрипт в отдельном файле, а потом подключить его с помощью конструкции
<head>
<script type=""application/javascript"" src=""http://Путь_к_файлу_со_скриптом"">
</script>
</head>

== Какие атрибуты имеет элемент script?

Элемент script, широко используемый для подключения к странице JavaScript, имеет несколько атрибутов.
- необязательный атрибут type для указания MIME-типа содержимого. В запросе комментариев RFC-4329, определяющем MIME-тип, соответствующий JavaScript, указаны медиа типы application/javascript и application/ecmascript, которые также определяются в этом документе, предназначены для практического использования, им следует отдавать предпочтение.
- необязательный атрибут src, принимающий в качестве значения адрес к файлу со скриптом.
- необязательный атрибут charset, используемый вместе с src для указания используемой кодировки внешнего файла.
- необязательный атрибут defer указывает, что получение скрипта происходит асинхронно, но выполнение следует отложить до тех пор, пока страница не будет загружена целиком.
- необязательный атрибут async указывает, что получение скрипта происходит асинхронно, а выполнение будет произведено сразу по завершению скачивания. Очерёдность выполнения скриптов не гарантируется.

== Что такое MIME?

Стандарт, описывающий передачу различных типов данных по электронной почте, а также, в общем случае, спецификация для кодирования информации и форматирования сообщений таким образом, чтобы их можно было пересылать по Интернету.

== Как используется JS в web-приложении?

JavaScript используется в клиентской части веб-приложений: клиент-серверных программ, в котором клиентом является браузер, а сервером — веб-сервер, имеющих распределённую между сервером и клиентом логику. Обмен информацией в веб-приложениях происходит по сети. Одним из преимуществ такого подхода является тот факт, что клиенты не зависят от конкретной операционной системы пользователя, поэтому веб-приложения являются кроссплатформенными сервисами.

== Как используется JS в AJAX?

JavaScript используется в AJAX, популярном подходе к построению интерактивных пользовательских интерфейсов веб-приложений, заключающемся в «фоновом» асинхронном обмене данными браузера с веб-сервером. В результате при обновлении данных веб-страница не перезагружается полностью и интерфейс веб-приложения становится быстрее, чем это происходит при традиционном подходе (без применения AJAX).
