= interview-helper

link:http://ec2-3-71-2-193.eu-central-1.compute.amazonaws.com:8080/ih/[Interview Helper^]

== Description

В рамках данного проекта разрабатывается система, которая призвана помочь специалистам повысить свой уровень подготовки к устному интервью или провести само интервью в какой-либо области, теме или вопросе. Стоит учитывать что такая возможность предоставляется по мере наполнения системы контентом (т.е. областями, темами и вопросами). За наполнение системы контентом отвечают сами пользователи системы.

=== Какую проблему данный проект решает или что нового приносит для пользователей?

* Помогает подготовиться к устному интервью как интервьюируемый
* Помогает провести устное интервью как интервьюер
* Позволяет влиять/управлять вопросами, темами и областями, что дает возможность работать с наиболее актуальными вопросами и темами в какой-то области
* Позволяет формировать статистику по вопросам, за счет обратной связи после интервью, что дает возможность работать с наиболее актуальными вопросами и темами в какой-то области

=== Потенциальные пользователи

* Начинающие специалисты, которые желают подготовиться к интервью
* Специалисты, которые проводят интервью

=== Аналогичные приложения

* Различные web-resource со статическим размещением вопросов и ответов
* YouTube channel, на которых специалисты проводят online-интервью
* Различные группы в messengers посвященные вопросам к интервью

=== Конкурентное преимущество

* Управление темами и вопросами, а не статическое размещение вопросов
* Доступность системы по нескольким каналам (web, mobile)
* Возможность дать обратную связь после интервью о том, какие вопросы были заданы
* Статистика по вопросам, частота просмотра и обращения за ответом

== Бизнес анализ

=== User Stories

link:https://miro.com/app/board/uXjVOY8hA_k=/?invite_link_id=177006962450[Mind Map^]

=== UML class diagram

link:./interview-helper.drawio[UML Class Diagram with draw.io]
