spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/interview_helper
    username: postgres
    password: postgres
  liquibase:
    change-log: db/changelog/master.yaml
